feat: change code for cakephp5

diff --git a/bin/cake b/bin/cake
--- a/bin/cake
+++ b/bin/cake
@@ -33,8 +33,37 @@ canonicalize() {
 	echo "$NAME"
 }
 
+# Find a CLI version of PHP
+findCliPhp() {
+    for TESTEXEC in php php-cli /usr/local/bin/php
+    do
+        SAPI=$(echo "<?= PHP_SAPI ?>" | $TESTEXEC 2>/dev/null)
+        if [ "$SAPI" = "cli" ]
+        then
+            echo $TESTEXEC
+            return
+        fi
+    done
+    echo "Failed to find a CLI version of PHP; falling back to system standard php executable" >&2
+    echo "php";
+}
+
+# If current path is a symlink, resolve to real path
+realname="$0"
+if [ -L "$realname" ]
+then
+	realname=$(readlink -f "$0")
+fi
+
 CONSOLE=$(dirname -- "$(canonicalize "$0")")
 APP=$(dirname "$CONSOLE")
+
+# If your CLI PHP is somewhere that this doesn't find, you can define a PHP environment
+# variable with the correct path in it.
+if [ -z "$PHP" ]
+then
+    PHP=$(findCliPhp)
+fi
 
 if [ $(basename $0) != 'cake' ]
 then
